# Generated by Django 2.1.7 on 2019-04-18 09:17

from django.db import migrations, models
import lbgmanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('main_organiser_id', models.CharField(max_length=10)),
                ('admins_ids', models.TextField()),
                ('tasks_ids', models.TextField(blank=True, null=True)),
                ('organisers_ids', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hashed_password', models.CharField(max_length=255)),
                ('auth_key', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=30)),
                ('responsibility', models.CharField(blank=True, choices=[(lbgmanager.models.Responsibility('President'), 'President'), (lbgmanager.models.Responsibility('Treasurer'), 'Treasurer'), (lbgmanager.models.Responsibility('Secretary'), 'Secretary'), (lbgmanager.models.Responsibility('Vice President in Public Relations'), 'Vice President in Public Relations'), (lbgmanager.models.Responsibility('Vice President in Human Resources'), 'Vice President in Human Resources'), (lbgmanager.models.Responsibility('Vice President in Foundraising'), 'Vice President in Foundraising')], max_length=50, null=True)),
                ('administrator', models.BooleanField(default=False)),
                ('finished_tasks', models.IntegerField(default=0)),
                ('dodged_tasks', models.IntegerField(default=0)),
                ('not_respected_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('responsibles_ids', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
