# Generated by Django 2.1.7 on 2019-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbgmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='responsibility',
            field=models.CharField(blank=True, choices=[('PR', 'President'), ('TR', 'Treasurer'), ('SEC', 'Secretary'), ('VP_PR', 'Vice President in Public Relations'), ('VP_HR', 'Vice President in Human Resources'), ('VP_FR', 'Vice President in Foundraising')], max_length=50, null=True),
        ),
    ]
